# Generated by Django 5.1.4 on 2025-01-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_job_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='post_subjob',
            field=models.ManyToManyField(blank=True, related_name='post_subjobs', to='api.post'),
        ),
    ]
