# Generated by Django 5.1.4 on 2025-01-15 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_job_post_subjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjobs', to='api.job')),
            ],
        ),
    ]
