# Generated by Django 5.1.4 on 2025-01-15 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_subjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.SmallIntegerField()),
                ('lincedin', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rating', models.SmallIntegerField()),
                ('cv', models.FileField(upload_to='employees/cv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
