# Generated by Django 5.1.4 on 2025-01-17 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sub_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='api.subjob'),
        ),
    ]
