# Generated by Django 5.1.4 on 2025-01-17 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_employee_sub_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sub_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='api.subjob'),
        ),
    ]
